services:
  db:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./.docker/sql:/docker-entrypoint-initdb.d/
      - ./.docker/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
