services:
  db:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./.docker/sql:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: test_pass
      POSTGRES_USER: test_user
      POSTGRES_DB: test_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d test_db -U test_user"]
      interval: 1s
      timeout: 5s
      retries: 10
